# Generated by Django 4.1 on 2022-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metro",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=150)),
                ("LineId", models.IntegerField()),
                ("LineName", models.IntegerField()),
                ("Description", models.CharField(max_length=120)),
                ("Order", models.IntegerField()),
                ("IsActive", models.BooleanField(default=True)),
                ("BabyRoom", models.BooleanField(default=True)),
                ("WC", models.BooleanField(default=True)),
                ("Masjid", models.BooleanField(default=True)),
                ("Longitude", models.FloatField()),
                ("Latitude", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(name="Makale",),
    ]
