# Generated by Django 4.1 on 2022-08-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0003_rename_id_metro_id"),
    ]

    operations = [
        migrations.RenameField(model_name="metro", old_name="Id", new_name="id",),
    ]
