# Generated by Django 4.1 on 2022-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0004_rename_id_metro_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metro", name="Latitude", field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="metro", name="LineName", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="metro",
            name="Longitude",
            field=models.CharField(max_length=120),
        ),
    ]
