# Generated by Django 4.1 on 2022-08-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0005_alter_metro_latitude_alter_metro_linename_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="metro", table="Metro",),
    ]
