# Generated by Django 4.1 on 2022-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0007_metro_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metro1",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=150)),
                ("LineId", models.IntegerField()),
                ("LineName", models.CharField(max_length=10)),
                ("Description", models.CharField(max_length=120)),
                ("Order", models.IntegerField()),
                ("IsActive", models.BooleanField(default=True)),
                ("BabyRoom", models.BooleanField(default=True)),
                ("WC", models.BooleanField(default=True)),
                ("Masjid", models.BooleanField(default=True)),
                ("Longitude", models.CharField(max_length=120)),
                ("Latitude", models.CharField(max_length=120)),
                (
                    "image",
                    models.ImageField(
                        default="./static/img/Istanbul_Metro_Logo.svg.png", upload_to=""
                    ),
                ),
            ],
            options={"db_table": "Metro1",},
        ),
    ]
