# Generated by Django 4.1 on 2022-08-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0008_metro1"),
    ]

    operations = [
        migrations.RemoveField(model_name="metro1", name="BabyRoom",),
        migrations.RemoveField(model_name="metro1", name="Latitude",),
        migrations.RemoveField(model_name="metro1", name="Longitude",),
        migrations.RemoveField(model_name="metro1", name="Masjid",),
        migrations.RemoveField(model_name="metro1", name="WC",),
        migrations.RemoveField(model_name="metro1", name="image",),
    ]
