# Generated by Django 4.1 on 2022-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0009_remove_metro1_babyroom_remove_metro1_latitude_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Metro1",),
    ]
