# Generated by Django 4.1 on 2022-08-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0011_hastane_alter_metro_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hastane",
            name="ILCE_ADI",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="hastane",
            name="Latitude",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="hastane",
            name="Longitude",
            field=models.CharField(max_length=150),
        ),
    ]
