# Generated by Django 4.1 on 2022-08-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0012_alter_hastane_ilce_adi_alter_hastane_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="hastane", old_name="_id", new_name="id",),
        migrations.AlterField(
            model_name="hastane", name="ACIL_SERVIS", field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="hastane", name="AMBULANS", field=models.BooleanField(),
        ),
    ]
