# Generated by Django 4.1 on 2022-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0013_rename__id_hastane_id_alter_hastane_acil_servis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hastane",
            name="Latitude",
            field=models.FloatField(max_length=150),
        ),
        migrations.AlterField(
            model_name="hastane",
            name="Longitude",
            field=models.FloatField(max_length=150),
        ),
    ]
