# Generated by Django 4.1 on 2022-08-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrolar", "0015_alter_hastane_latitude_alter_hastane_longitude"),
    ]

    operations = [
        migrations.DeleteModel(name="Hastane",),
    ]
